"""empty message

Revision ID: 47910892b38e
Revises: ca7a9450dadc
Create Date: 2024-07-22 19:04:53.555414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47910892b38e'
down_revision = 'ca7a9450dadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('order_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_relation', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('photo_relation', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'order', ['order_relation'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'photo', ['photo_relation'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('photo_relation')
        batch_op.drop_column('order_relation')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('order_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
